### ISSUE TITLE
Support CKB/SUDT transfer to Ethereum ERC20

### ISSUE THREAD

**Issue by huwenchao** [nervosnetwork/force-bridge#217]
## tasks

- [ ] solution documentation
- [ ] offchain module
  - [ ] db
  - [ ] monitor
- [ ] ETH contract
  - [ ] ERC20 contract(support mint with multisig owner)
  - [ ] optional: factory contract to create new ERC20 contract. We can also do this in offchain module
  - [ ] manage contract: mapping Nervos assets to Ethereum assets, handle committee change, etc
- [ ] [rc lock](https://github.com/nervosnetwork/ckb-production-scripts/pull/38) generator. The new version of rc lock supports changing committee without change the lockscript itself. We should use it instead of normal multisig lock in CKB handler.
- [ ] UI. Should be integrated with [existing UI](forcebridge.com).
